# Generated by Django 5.0.7 on 2024-07-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_address_order_remove_supplier_address_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
        migrations.AddField(
            model_name='supplier',
            name='street_address',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
