# Generated by Django 5.0.7 on 2024-07-16 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_supplier_address_supplier_street_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='secondary_address',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='card_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerbillingaddress',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_addresses', to='main.customer'),
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to='main.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.card'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.warehouse'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.supplier'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.address'),
        ),
    ]
