# Generated by Django 5.0.7 on 2024-07-25 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_product_image_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='isCustomer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customer'),
        ),
    ]
