# Generated by Django 5.0.7 on 2024-07-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_address_iscustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_no',
            field=models.BigIntegerField(),
        ),
    ]
