# Generated by Django 5.0.7 on 2024-07-29 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_card_card_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customershippingaddress',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customershippingaddress',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_orders', to='main.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_orders', to='main.address'),
        ),
        migrations.DeleteModel(
            name='CustomerBillingAddress',
        ),
        migrations.DeleteModel(
            name='CustomerShippingAddress',
        ),
    ]
