# Generated by Django 5.0.7 on 2024-07-29 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_customershippingaddress_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryplan',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryplan',
            name='delivery_date',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='deliveryplan',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order'),
        ),
        migrations.AlterField(
            model_name='deliveryplan',
            name='ship_date',
            field=models.CharField(),
        ),
    ]
