# Generated by Django 5.0.7 on 2024-07-29 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_deliveryplan_id_alter_deliveryplan_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryplan',
            name='id',
        ),
        migrations.AlterField(
            model_name='deliveryplan',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.order'),
        ),
    ]
