# Generated by Django 5.0.7 on 2024-07-29 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_deliveryplans_delete_deliveryplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryPlan',
        ),
    ]
