# Generated by Django 5.0.7 on 2024-07-29 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_delete_deliveryplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPlan',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.order')),
                ('delivery_type', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('ship_date', models.DateField()),
                ('delivery_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_order', to='main.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ship_order', to='main.address'),
        ),
        migrations.DeleteModel(
            name='DeliveryPlans',
        ),
    ]
