# Generated by Django 5.0.7 on 2024-07-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_deliveryplan_alter_order_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryplan',
            name='delivery_date',
            field=models.CharField(),
        ),
    ]
