# Generated by Django 5.0.7 on 2024-07-29 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_deliveryplan_delivery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPlans',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.order')),
                ('delivery_type', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('ship_date', models.DateField()),
                ('delivery_date', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='DeliveryPlan',
        ),
    ]
