# Generated by Django 5.0.7 on 2024-07-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_deliveryplans_delete_deliveryplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryplans',
            name='ship_date',
            field=models.CharField(),
        ),
    ]
