# Generated by Django 5.0.7 on 2024-07-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_deliveryplans_ship_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryplans',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
