# Generated by Django 5.0.7 on 2024-07-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_deliveryplans_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryplans',
            name='price',
        ),
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
