# Generated by Django 5.0.7 on 2024-07-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_deliveryplans_price_alter_customer_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryplans',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
