# Generated by Django 5.0.7 on 2024-07-30 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_deliveryplans_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='balance',
            new_name='balance2',
        ),
    ]
