# Generated by Django 5.0.7 on 2024-07-30 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_rename_balance_customer_balance2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='balance2',
            new_name='balance',
        ),
    ]
