# Generated by Django 5.0.7 on 2024-08-02 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_customer_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='picture_address',
        ),
    ]
